spring.application.name=Restaurants

server.port=8080

# Configuración para MySQL Local (localhost)
spring.datasource.url=jdbc:mysql://localhost:3306/Prueba?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Driver de conexión
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Propiedades de Hibernate para desarrollo local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true