spring.application.name=Restaurants
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gondola.proxy.rlwy.net:34354/railway}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:ycLVGabXKvmeSxlmXfydoPgXpmbvnJsW}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración de Hibernate (Crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

