spring.application.name=Restaurants
spring.datasource.url=mysql://root:YeVwxHSNhOHmOwZFrtmktqOHshocgCOP@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=YeVwxHSNhOHmOwZFrtmktqOHshocgCOP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver